/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface createSample {
  body: {
    age: number;
    name: string;
  };
  query?: {
    name?: string;
  };
  user?: {
    permissions?: any;
  };
}

export interface deleteSample {
  body?: {
    age?: number;
    name?: string;
  };
  query: {
    name?: string;
  };
  user?: {
    permissions?: any;
  };
}

export interface getSample {
  body?: {
    age?: number;
    name?: string;
  };
  query: {
    name?: string;
  };
  user?: {
    permissions?: any;
  };
}

export interface getSamples {
  body?: {
    age?: number;
    name?: string;
  };
  query: {
    name?: string;
  };
  user?: {
    permissions?: any;
  };
}

export interface updateSample {
  body: {
    age?: number;
    name?: string;
  };
  query: {
    name?: string;
  };
  user?: {
    permissions?: any;
  };
}
