/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface createSample {
  age: number;
  name: string;
}

export type deleteSample = boolean;

export interface getSample {
  age: number;
  name: string;
}

export type getSamples = {
  age: number;
  name: string;
}[];

export type updateSample = boolean;
