/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface login {
  token: string;
}

export interface user {
  id?: string;
  permissions?: any;
}
