/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface base {
  body?: any;
  query: {
    createdAt?: string | Date;
    message?: string;
    receiver?: string;
    sender?: string;
    updatedAt?: string | Date;
  };
  user: {
    id?: string;
    permissions?: any;
  };
}

export type date = string | Date;

export interface message {
  createdAt?: string | Date;
  message?: string;
  receiver?: string;
  sender?: string;
  updatedAt?: string | Date;
}

export interface messageRequired {
  createdAt?: string | Date;
  message: string;
  receiver: string;
  sender: string;
  updatedAt?: string | Date;
}

export interface query {
  createdAt?: string | Date;
  message?: string;
  receiver?: string;
  sender?: string;
  updatedAt?: string | Date;
}

export interface sendMessage {
  createdAt?: string | Date;
  message: string;
  receiver: string;
  updatedAt?: string | Date;
}
