/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface deleteMessage {
  body?: any;
  query: {
    createdAt?: string | Date;
    message?: string;
    receiver?: string;
    sender?: string;
    updatedAt?: string | Date;
  };
  user: {
    permissions?: any;
  };
}

export interface getMessage {
  body?: any;
  query: {
    createdAt?: string | Date;
    message?: string;
    receiver?: string;
    sender?: string;
    updatedAt?: string | Date;
  };
  user: {
    permissions?: any;
  };
}

export interface getMessages {
  body?: any;
  query: {
    createdAt?: string | Date;
    message?: string;
    receiver?: string;
    sender?: string;
    updatedAt?: string | Date;
  };
  user: {
    permissions?: any;
  };
}

export interface sendMessage {
  body?: {
    createdAt?: string | Date;
    message: string;
    receiver: string;
    sender: string;
    updatedAt?: string | Date;
  };
  query: {
    createdAt?: string | Date;
    message?: string;
    receiver?: string;
    sender?: string;
    updatedAt?: string | Date;
  };
  user: {
    permissions?: any;
  };
}

export interface updateMessage {
  body?: {
    createdAt?: string | Date;
    message?: string;
    receiver?: string;
    sender?: string;
    updatedAt?: string | Date;
  };
  query: {
    createdAt?: string | Date;
    message?: string;
    receiver?: string;
    sender?: string;
    updatedAt?: string | Date;
  };
  user: {
    permissions?: any;
  };
}
