/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface createMessage {
  createdAt?: string | Date;
  message: string;
  receiver: string;
  sender: string;
  updatedAt?: string | Date;
}

export type deleteMessage = boolean;

export interface getMessage {
  createdAt?: string | Date;
  message: string;
  receiver: string;
  sender: string;
  updatedAt?: string | Date;
}

export type getMessages = ({
  createdAt?: string | Date;
  message: string;
  receiver: string;
  sender: string;
  updatedAt?: string | Date;
})[];

export interface sendMessage {
  createdAt?: string | Date;
  message: string;
  receiver: string;
  sender: string;
  updatedAt?: string | Date;
}

export type updateMessage = boolean;
