/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export type deleteMessage = boolean;

export interface getMessage {
  message: string;
  receiver: string;
  sender: string;
}

export type getMessages = {
  message: string;
  receiver: string;
  sender: string;
}[];

export type sendMessage = boolean;

export type updateMessage = boolean;
